### ISSUE TITLE
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)`

### ISSUE THREAD

**Issue by 7W7W7W** [imatif17/Prototype-Mean-Teacher#4]
Hello, thank you for your open source project. I have encountered this problem. How can I fix it?
`Traceback (most recent call last):
  File "train_net.py", line 58, in <module>
    launch(
  File "/root/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net.py", line 52, in main
    return trainer.train()
  File "/root/autodl-tmp/Prototype-Mean-Teacher/pmteacher/engine/trainer.py", line 184, in train
    self.train_loop(self.start_iter, self.max_iter)
  File "/root/autodl-tmp/Prototype-Mean-Teacher/pmteacher/engine/trainer.py", line 199, in train_loop
    self.run_step_full_semisup()
  File "/root/autodl-tmp/Prototype-Mean-Teacher/pmteacher/engine/trainer.py", line 327, in run_step_full_semisup
    record_dict, _, _, _ = self.model(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/Prototype-Mean-Teacher/pmteacher/modeling/meta_arch/rcnn.py", line 423, in forward
    loss_D_img_s = criterion(D_img_out_s, torch.FloatTensor(D_img_out_s.data.size()).fill_(source_label).to(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)`

**Comment by 7W7W7W** [comment]
Hello, I have encountered many problems, but the final result is like this

`[05/09 09:29:23 d2.data.build]: Distribution of instances among all 20 categories:
|  category   | #instances   |  category   | #instances   |  category  | #instances   |
|:-----------:|:-------------|:-----------:|:-------------|:----------:|:-------------|
|  aeroplane  | 175          |   bicycle   | 216          |    bird    | 305          |
|    boat     | 190          |   bottle    | 296          |    bus     | 141          |
|     car     | 818          |     cat     | 198          |   chair    | 706          |
|     cow     | 171          | diningtable | 162          |    dog     | 267          |
|    horse    | 199          |  motorbike  | 197          |   person   | 2742         |
| pottedplant | 320          |    sheep    | 162          |    sofa    | 207          |
|    train    | 170          |  tvmonitor  | 176          |            |              |
|    total    | 7818         |             |              |            |              |
[05/09 09:29:23 d2.data.common]: Serializing 2510 elements to byte tensors and concatenating them all ...
[05/09 09:29:23 d2.data.common]: Serialized dataset takes 1.13 MiB
[05/09 09:29:23 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(600, 600), max_size=1333, sample_style='choice')]
[05/09 09:29:23 d2.evaluation.evaluator]: Start inference on 2510 batches
/root/miniconda3/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[05/09 09:29:24 d2.evaluation.evaluator]: Inference done 11/2510. Dataloading: 0.0007 s/iter. Inference: 0.0219 s/iter. Eval: 0.0008 s/iter. Total: 0.0234 s/iter. ETA=0:00:58
[05/09 09:29:29 d2.evaluation.evaluator]: Inference done 226/2510. Dataloading: 0.0010 s/iter. Inference: 0.0216 s/iter. Eval: 0.0007 s/iter. Total: 0.0233 s/iter. ETA=0:00:53
[05/09 09:29:34 d2.evaluation.evaluator]: Inference done 433/2510. Dataloading: 0.0012 s/iter. Inference: 0.0218 s/iter. Eval: 0.0007 s/iter. Total: 0.0237 s/iter. ETA=0:00:49
[05/09 09:29:39 d2.evaluation.evaluator]: Inference done 631/2510. Dataloading: 0.0014 s/iter. Inference: 0.0220 s/iter. Eval: 0.0008 s/iter. Total: 0.0243 s/iter. ETA=0:00:45
[05/09 09:29:44 d2.evaluation.evaluator]: Inference done 828/2510. Dataloading: 0.0015 s/iter. Inference: 0.0221 s/iter. Eval: 0.0008 s/iter. Total: 0.0245 s/iter. ETA=0:00:41
[05/09 09:29:49 d2.evaluation.evaluator]: Inference done 1024/2510. Dataloading: 0.0016 s/iter. Inference: 0.0222 s/iter. Eval: 0.0008 s/iter. Total: 0.0247 s/iter. ETA=0:00:36
[05/09 09:29:54 d2.evaluation.evaluator]: Inference done 1221/2510. Dataloading: 0.0017 s/iter. Inference: 0.0223 s/iter. Eval: 0.0009 s/iter. Total: 0.0248 s/iter. ETA=0:00:32
[05/09 09:29:59 d2.evaluation.evaluator]: Inference done 1417/2510. Dataloading: 0.0017 s/iter. Inference: 0.0223 s/iter. Eval: 0.0009 s/iter. Total: 0.0249 s/iter. ETA=0:00:27
[05/09 09:30:04 d2.evaluation.evaluator]: Inference done 1614/2510. Dataloading: 0.0017 s/iter. Inference: 0.0224 s/iter. Eval: 0.0009 s/iter. Total: 0.0250 s/iter. ETA=0:00:22
[05/09 09:30:09 d2.evaluation.evaluator]: Inference done 1809/2510. Dataloading: 0.0018 s/iter. Inference: 0.0224 s/iter. Eval: 0.0009 s/iter. Total: 0.0251 s/iter. ETA=0:00:17
[05/09 09:30:14 d2.evaluation.evaluator]: Inference done 2006/2510. Dataloading: 0.0018 s/iter. Inference: 0.0224 s/iter. Eval: 0.0009 s/iter. Total: 0.0251 s/iter. ETA=0:00:12
[05/09 09:30:19 d2.evaluation.evaluator]: Inference done 2201/2510. Dataloading: 0.0018 s/iter. Inference: 0.0225 s/iter. Eval: 0.0009 s/iter. Total: 0.0252 s/iter. ETA=0:00:07
[05/09 09:30:24 d2.evaluation.evaluator]: Inference done 2399/2510. Dataloading: 0.0018 s/iter. Inference: 0.0225 s/iter. Eval: 0.0009 s/iter. Total: 0.0252 s/iter. ETA=0:00:02
[05/09 09:30:27 d2.evaluation.evaluator]: Total inference time: 0:01:03.273656 (0.025259 s / iter per device, on 1 devices)
[05/09 09:30:27 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:56 (0.022467 s / iter per device, on 1 devices)
[05/09 09:30:54 d2.engine.defaults]: Evaluation results for Night_val in csv format:
[05/09 09:30:54 d2.evaluation.testing]: copypaste: Task: bbox
[05/09 09:30:54 d2.evaluation.testing]: copypaste: AP,AP50,AP75
[05/09 09:30:54 d2.evaluation.testing]: copypaste: 0.6911,1.9696,0.2878`

This result should be incorrect. Is it because I modified the code in some part? I used the VOC2007 dataset to create three types of data for training: day time, night, and organization

**Comment by imatif17** [comment]
Hello, Sorry I missed your first issue. Is it resolved?

For the second issue, how did you created 3 types of data from VOC2007? I don't think there is day time, night and organization in that dataset. Also, I don't understand the issue, from the your final results I think it's doing the inference correctly, isn't it?

**Comment by 7W7W7W** [comment]
> Hello, Sorry I missed your first issue. Is it resolved?
> 
> For the second issue, how did you created 3 types of data from VOC2007? I don't think there is day time, night and organization in that dataset. Also, I don't understand the issue, from the your final results I think it's doing the inference correctly, isn't it?

Thank you very much for your reply. The problems encountered during the training process have been resolved. Although I am not sure which changes will affect the results, in the end, it can be achieved. The results are as described above.

For the three types of data, I used VOC2007 as the daytime, and then generated night and foggy by adjusting image brightness and using atmospheric scattering models. The labels for these three types are the same.

In the above results, AP50=1.9696, which is incorrect, right? Because it should be a value between 0 and 1, it confuses me. (I have just started deep learning and don't quite understand. Thank you again.)

**Comment by imatif17** [comment]
AP50 = 1.9696 is correct it can be between 0 and 100. I think you got this result without any training. Also, as you're training on your own dataset, you have to make suitable changes in the code. Firstly, you have to write a code for data loader (I think you have done that). Also, you have to change the evaluation type (line 148 in trainer). Then, make suitable changes in the config file (for example number of classes). As you're using Pascal VOC, please check this repository (https://github.com/facebookresearch/adaptive_teacher/tree/main)

**Comment by 7W7W7W** [comment]
> AP50 = 1.9696 is correct it can be between 0 and 100. I think you got this result without any training. Also, as you're training on your own dataset, you have to make suitable changes in the code. Firstly, you have to write a code for data loader (I think you have done that). Also, you have to change the evaluation type (line 148 in trainer). Then, make suitable changes in the config file (for example number of classes). As you're using Pascal VOC, please check this repository (https://github.com/facebookresearch/adaptive_teacher/tree/main)

Thank you very much for your help.！
How to handle the specific issue of "change the evaluation type"? I have found that the model has been using bdd_evaluation.py. How can I replace it with another file? My recent results show missing metrics, such as [05/15 08:30:49 d2. engine. defaults]: Evaluation results for Night_val in CSV format:
(base) root@autodl-container-ddc311903c-010872b4 :~/autodl tmp/Prototype Mean Thatcher #, I'm confused.

Also, may I ask how to visualize the results? The error in the pic.py file is: NameError: name 'trainer' is not defined

**Comment by judyxt** [comment]
> Hello, thank you for your open source project. I have encountered this problem. How can I fix it? `Traceback (most recent call last): File "train_net.py", line 58, in <module> launch( File "/root/detectron2/detectron2/engine/launch.py", line 82, in launch main_func(*args) File "train_net.py", line 52, in main return trainer.train() File "/root/autodl-tmp/Prototype-Mean-Teacher/pmteacher/engine/trainer.py", line 184, in train self.train_loop(self.start_iter, self.max_iter) File "/root/autodl-tmp/Prototype-Mean-Teacher/pmteacher/engine/trainer.py", line 199, in train_loop self.run_step_full_semisup() File "/root/autodl-tmp/Prototype-Mean-Teacher/pmteacher/engine/trainer.py", line 327, in run_step_full_semisup record_dict, _, _, _ = self.model( File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/root/autodl-tmp/Prototype-Mean-Teacher/pmteacher/modeling/meta_arch/rcnn.py", line 423, in forward loss_D_img_s = criterion(D_img_out_s, torch.FloatTensor(D_img_out_s.data.size()).fill_(source_label).to( File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1150, in forward return F.cross_entropy(input, target, weight=self.weight, File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 2846, in cross_entropy return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing) IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)`

Hello, I met the same error, may i  ask how to solve it?
